;;; -*- coding: utf-8 -*-
;;; ots-keys.el

(require 'ots-normal)
(require 'ots-util)

(defun ots-keys-set-basic ()
  "Set basic global keybindings."
  (global-set-key (kbd "C-1") 'delete-other-windows)
  (global-set-key (kbd "C-2") 'split-window-vertically)
  (global-set-key (kbd "C-3") 'split-window-horizontally)
  (global-set-key (kbd "C-0") 'delete-window)
  (global-set-key (kbd "C-a") 'mark-whole-buffer)
  (global-set-key (kbd "C-b") 'ots-util-smart-home)
  (global-set-key (kbd "C-e") 'end-of-line)
  (global-set-key (kbd "C-f") 'isearch-forward-regexp)
  (global-set-key (kbd "C-S-f") 'isearch-backward-regexp)
  (global-set-key (kbd "C-g") 'isearch-repeat-forward)
  (global-set-key (kbd "C-S-g") 'isearch-repeat-backward)
  (global-set-key (kbd "C-h") 'query-replace-regexp)
  (global-set-key (kbd "C-S-h") 'replace-regexp)
  (global-set-key (kbd "C-j") 'join-line)
  (global-set-key (kbd "C-S-j") 'join-line)
  (global-set-key (kbd "C-k") 'comment-or-uncomment-region)
  (global-set-key (kbd "C-l") 'goto-line)
  (global-set-key (kbd "C-S-l") 'helm-occur)
  (global-set-key (kbd "C-m") 'exchange-point-and-mark)
  (global-set-key (kbd "M-m") 'menu-bar-mode)
  (global-set-key (kbd "C-n") 'universal-argument)
  (global-set-key (kbd "C-o") 'helm-find-files)
  (global-set-key (kbd "C-p") 'mark-paragraph)
  (global-set-key (kbd "C-S-p") 'mark-defun)
  (global-set-key (kbd "C-q") 'save-buffers-kill-emacs)
  (global-set-key (kbd "C-S-q") 'kill-emacs)
  (global-set-key (kbd "C-r") 'sort-lines)
  (global-set-key (kbd "C-S-r") 'sort-paragraphs)
  (global-set-key (kbd "C-s") 'ots-util-save-buffer)
  (global-set-key (kbd "C-S-s") 'write-file)
  (global-set-key (kbd "C-t") 'find-tag)
  (global-set-key (kbd "C-S-t") 'pop-tag-mark)
  (global-set-key (kbd "C-u") 'upcase-region)
  (global-set-key (kbd "C-S-u") 'downcase-region)
  (global-set-key (kbd "C-S-v") 'yank-pop)
  (global-set-key (kbd "C-w") 'ots-util-kill-buffer)
  (global-set-key (kbd "C-S-w") 'browse-url-at-point)
  (global-set-key (kbd "M-x") 'helm-M-x)
  (global-set-key (kbd "C-y") 'ots-util-smart-fill)
  (global-set-key (kbd "C-S-z") 'redo)
  (global-set-key (kbd "§") 'ots-util-match-paren)
  (global-set-key (kbd "C-§") 'helm-buffers-list)
  (global-set-key (kbd "M-§") 'ots-util-switch-to-other-buffer)
  (global-set-key (kbd "C--") 'hs-toggle-hiding)
  (global-set-key (kbd "C-SPC") 'set-mark-command)
  (global-set-key (kbd "<tab>") 'ots-util-smart-tab)
  (global-set-key (kbd "<C-tab>") 'ots-util-next-window)
  (global-set-key (kbd "<S-tab>") 'ots-util-previous-window)
  (global-set-key (kbd "<S-iso-lefttab>") 'ots-util-previous-window)
  (global-set-key (kbd "<C-S-tab>") 'ots-util-insert-tab)
  (global-set-key (kbd "<C-iso-lefttab>") 'ots-util-insert-tab)
  (global-set-key (kbd "<delete>") 'delete-char)
  (global-set-key (kbd "<home>") 'ots-util-smart-home)
  (global-set-key (kbd "<C-kp-subtract>") 'ots-util-insert-en-dash)
  (global-set-key (kbd "<C-S-kp-subtract>") 'ots-util-insert-em-dash)
  (global-set-key (kbd "<f1>") 'help)
  (global-set-key (kbd "<S-f1>") 'woman)
  (global-set-key (kbd "<f3>") 'ots-util-start-external-terminal)
  (global-set-key (kbd "<S-f3>") 'shell)
  (global-set-key (kbd "<f5>") 'compile)
  (global-set-key (kbd "<S-f5>") 'recompile)
  (global-set-key (kbd "<C-S-f5>") 'kill-compilation)
  (global-set-key (kbd "<f11>") 'ots-fullscreen-toggle))

(defun ots-keys-set-isearch ()
  "Set keybindings for using interactive search."
  (define-key isearch-mode-map (kbd "C-w") 'isearch-yank-word)
  (define-key isearch-mode-map (kbd "C-v") 'isearch-yank-kill)
  (define-key isearch-mode-map (kbd "<return>") 'isearch-exit)
  (define-key isearch-mode-map (kbd "<kp-enter>") 'isearch-exit))

(defun ots-keys-set-punct ()
  "Set keybindings for punctuation navigation keys."
  (if (derived-mode-p 'prog-mode)
      (ots-keys-set-punct-defun)
    (ots-keys-set-punct-sentence)))

(defun ots-keys-set-punct-defun ()
  "Set keybindings for navigating between functions."
  (local-set-key (kbd "C-,") 'beginning-of-defun)
  (local-set-key (kbd "C-;") 'ots-util-mark-to-beginning-of-defun)
  (local-set-key (kbd "C-.") 'end-of-defun)
  (local-set-key (kbd "C-:") 'ots-util-mark-to-end-of-defun))

(defun ots-keys-set-punct-sentence ()
  "Set keybindings for navigating between sentences."
  (local-set-key (kbd "C-,") 'backward-sentence)
  (local-set-key (kbd "C-;") 'ots-util-mark-to-beginning-of-sentence)
  (local-set-key (kbd "C-.") 'forward-sentence)
  (local-set-key (kbd "C-:") 'ots-util-mark-to-end-of-sentence))

(defun ots-keys-set-text ()
  "Set keybindings for editing text."
  (dolist (mode ots-normal-modes)
    (when (derived-mode-p mode)
      (local-set-key (kbd "C-d") 'ots-util-smart-kill-line)
      (local-set-key (kbd "C-S-d") 'ots-util-smart-kill-word)
      (local-set-key (kbd "<return>") 'newline-and-indent)
      (local-set-key (kbd "<kp-enter>") 'newline-and-indent))))

(cua-mode t)
(setq cua-keep-region-after-copy t)
(ots-keys-set-basic)
(ots-keys-set-isearch)
(add-hook 'after-change-major-mode-hook 'ots-keys-set-punct)
(add-hook 'after-change-major-mode-hook 'ots-keys-set-text)

(provide 'ots-keys)
;;; ots-keys.el ends here
