;;; -*- coding: utf-8 -*-
;;; ots-lsp-mode.el

(setq company-lsp-cache-candidates nil)
(setq company-lsp-enable-snippet nil)
(setq lsp-auto-configure nil)
(setq lsp-auto-guess-root t)
(setq lsp-diagnostic-package :none)
(setq lsp-eldoc-enable-hover t)
(setq lsp-eldoc-render-all nil)
(setq lsp-enable-completion-at-point t)
(setq lsp-enable-folding nil)
(setq lsp-enable-imenu nil)
(setq lsp-enable-indentation nil)
(setq lsp-enable-snippet nil)
(setq lsp-flycheck-live-reporting nil)
(setq lsp-log-io t)
(setq lsp-pyls-plugins-autopep8-enabled nil)
(setq lsp-pyls-plugins-flake8-enabled nil)
(setq lsp-pyls-plugins-jedi-hover-enabled t)
(setq lsp-pyls-plugins-jedi-signature-help-enabled t)
(setq lsp-pyls-plugins-mccabe-enabled nil)
(setq lsp-pyls-plugins-pycodestyle-enabled nil)
(setq lsp-pyls-plugins-pydocstyle-enabled nil)
(setq lsp-pyls-plugins-pyflakes-enabled nil)
(setq lsp-pyls-plugins-pylint-enabled nil)
(setq lsp-pyls-plugins-rope-completion-enabled nil)
(setq lsp-pyls-plugins-yapf-enabled nil)
(setq lsp-restart 'auto-restart)
(setq lsp-signature-auto-activate t)
(setq lsp-signature-doc-lines 1)
(setq lsp-signature-render-documentation t)
(setq read-process-output-max (* 1024 1024))

;; (setq lsp-eldoc-hook nil)
;; (setq lsp-signature-function nil)

(provide 'ots-lsp-mode)
;;; ots-lsp-mode.el ends here
