;;; -*- coding: utf-8 -*-
;;; ots-theme-light.el

(deftheme ots-light)

(custom-theme-set-faces
 'ots-light

 ;; Base Emacs
 `(comint-highlight-prompt ((t (:foreground "#cc6666"))))
 `(compilation-column-number ((t (:foreground "#ba7fba"))))
 `(compilation-error ((t (:foreground "#ff405a"))))
 `(compilation-info ((t (:foreground "#1d77ff"))))
 `(compilation-line-number ((t (:foreground "#9f6fff"))))
 `(compilation-warning ((t (:foreground "#c4a000"))))
 `(cursor ((t (:background "#1d77ff"))))
 `(default ((t (:background "#f2ede0" :foreground "#444444"))))
 `(fringe ((t (:foreground "#1d77ff"))))
 `(header-line ((t (:background "#f2ede0"))))
 `(highlight ((t (:underline t))))
 `(isearch ((t (:background "#ffcc00" :foreground unspecified))))
 `(lazy-highlight ((t (:background "#e0e0e0" :foreground unspecified))))
 `(line-number ((t (:foreground "#bbbbbb"))))
 `(line-number-current-line ((t (:foreground "#bbbbbb"))))
 `(link ((t (:foreground "#897fba"))))
 `(minibuffer-prompt ((t (:foreground "#1d77ff"))))
 `(mode-line ((t (:background "#e4e0d3" :foreground "#999999" :box (:line-width 6 :color "#e4e0d3")))))
 `(mode-line-inactive ((t (:background "#e4e0d3" :foreground "#cccccc" :box (:line-width 6 :color "#e4e0d3")))))
 `(query-replace ((t (:background "#ffcc00" :foreground unspecified))))
 `(region ((t (:background "#f5f5aa" :foreground unspecified))))
 `(show-paren-match ((t (:background "#99eebb" :foreground unspecified))))
 `(show-paren-mismatch ((t (:background "#ff5555" :foreground unspecified))))
 `(vertical-border ((t (:foreground "#f2ede0"))))
 `(whitespace-space ((t (:background unspecified :foreground "#ff405a"))))
 `(whitespace-tab ((t (:background unspecified :foreground "#ff405a"))))

 ;; Font-lock
 `(font-lock-builtin-face ((t (:foreground "#ff6f87"))))
 `(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 `(font-lock-comment-face ((t (:foreground "#84a3c2"))))
 `(font-lock-constant-face ((t (:inherit font-lock-type-face))))
 `(font-lock-doc-string-face ((t (:inherit font-lock-comment-face))))
 `(font-lock-function-name-face ((t (:foreground "#1d77ff"))))
 `(font-lock-keyword-face ((t (:foreground "#897fba"))))
 `(font-lock-negation-char-face ((t (:inherit font-lock-function-name-face))))
 `(font-lock-preprocessor-face ((t (:inherit font-lock-function-name-face))))
 `(font-lock-property-use-face ((t (:foreground unspecified))))
 `(font-lock-regexp-grouping-backslash ((t (:inherit font-lock-keyword-face))))
 `(font-lock-regexp-grouping-construct ((t (:inherit font-lock-keyword-face))))
 `(font-lock-string-face ((t (:foreground "#ba7fba"))))
 `(font-lock-type-face ((t (:foreground "#00bb29"))))
 `(font-lock-variable-name-face ((t (:foreground "#b0a678"))))
 `(font-lock-warning-face ((t (:foreground "#ff405a"))))

 ;; Add-on packages
 `(copilot-overlay-face ((t (:foreground "#ff5555"))))
 `(corfu-annotations ((t (:foreground "#666666"))))
 `(corfu-bar ((t (:background unspecified))))
 `(corfu-border ((t (:background unspecified))))
 `(corfu-current ((t (:background "#527bcc" :foreground "#ffffff"))))
 `(corfu-default ((t (:background "#dddddd" :foreground "#666666"))))
 `(cua-rectangle ((t (:background "#f0f0aa" :foreground unspecified))))
 `(cua-rectangle-noselect ((t (:background "#cccccc" :foreground unspecified))))
 `(diff-added ((t (:background "#cbffcb" :foreground unspecified))))
 `(diff-file-header ((t (:background "#ffd9b3" :foreground unspecified))))
 `(diff-header ((t (:background "#ffffb3" :foreground unspecified))))
 `(diff-refine-added ((t (:background "#cbffcb" :foreground unspecified))))
 `(diff-refine-removed ((t (:background "#ffcbcb" :foreground unspecified))))
 `(diff-removed ((t (:background "#ffcbcb" :foreground unspecified))))
 `(eglot-highlight-symbol-face ((t (:weight normal))))
 `(ess-%op%-face ((t (:inherit font-lock-keyword-face))))
 `(ess-modifiers-face ((t (:inherit font-lock-builtin-face))))
 `(ess-operator-face ((t (:inherit font-lock-keyword-face))))
 `(fill-column-indicator ((t (:foreground "#bbbbbb"))))
 `(flycheck-error ((t (:underline "#ff5555"))))
 `(flycheck-info ((t (:underline "#ff5555"))))
 `(flycheck-warning ((t (:underline "#ff5555"))))
 `(font-latex-bold-face ((t (:background unspecified :foreground unspecified))))
 `(font-latex-italic-face ((t (:background unspecified :foreground unspecified))))
 `(font-latex-math-face ((t (:background unspecified :foreground unspecified))))
 `(font-latex-sedate-face ((t (:background unspecified :foreground "#9f6fff"))))
 `(font-latex-string-face ((t (:background unspecified :foreground unspecified))))
 `(font-latex-verbatim-face ((t (:background unspecified :foreground unspecified))))
 `(font-latex-warning-face ((t (:background unspecified :foreground "#ff405a"))))
 `(git-gutter:added ((t (:background "#88ff88" :foreground "#f2ede0"))))
 `(git-gutter:deleted ((t (:background "#ff8888" :foreground "#f2ede0"))))
 `(git-gutter:modified ((t (:background "#8888ff" :foreground "#f2ede0"))))
 `(jinx-misspelled ((t (:underline "#ff6f87"))))
 `(makefile-space ((t (:background "#ffd9b3" :foreground unspecified))))
 `(markdown-code-face ((t (:background unspecified :foreground "#ba7fba"))))
 `(markdown-header-face ((t (:foreground "#1d77ff" :weight bold))))
 `(markdown-inline-code-face ((t (:background unspecified :foreground "#ba7fba"))))
 `(mmm-default-submode-face ((t (:background unspecified :foreground unspecified))))
 `(neo-dir-link-face ((t (:background unspecified :foreground "#84a3c2"))))
 `(neo-file-link-face ((t (:background unspecified :foreground "#999999"))))
 `(neo-root-dir-face ((t (:background unspecified :foreground "#999999"))))
 `(orderless-match-face-0 ((t (:foreground "#ff8888"))))
 `(orderless-match-face-1 ((t (:foreground "#ff8888"))))
 `(orderless-match-face-2 ((t (:foreground "#ff8888"))))
 `(orderless-match-face-3 ((t (:foreground "#ff8888"))))
 `(popup-tip-face ((t (:background "#f0f080" :foreground "#303030"))))
 `(sh-heredoc ((t (:foreground "#ba7fba"))))
 `(sh-quoted-exec ((t (:foreground "#00bb29"))))
 `(tab-line ((t (:background "#f2ede0" :box (:line-width (1 . 10) :color "#f2ede0")))))
 `(tab-line-tab ((t (:inherit tab-line))))
 `(tab-line-tab-current ((t (:inherit tab-line :foreground "#111111"))))
 `(tab-line-tab-inactive ((t (:inherit tab-line :foreground "#999999"))))
 `(tab-line-tab-modified ((t (:foreground "#ff405a"))))
 `(tab-line-highlight ((t (:inherit tab-line-tab-current))))
 `(vertico-current ((t (:background "#f5f5aa" :foreground unspecified))))
 `(vertico-group-title ((t (:foreground "#1d77ff"))))
 `(vterm-color-black ((t (:foreground "#252525"))))
 `(vterm-color-blue ((t (:foreground "#3465a4"))))
 `(vterm-color-cyan ((t (:foreground "#06989a"))))
 `(vterm-color-green ((t (:foreground "#4e9a06"))))
 `(vterm-color-magenta ((t (:foreground "#75507b"))))
 `(vterm-color-red ((t (:foreground "#cc0000"))))
 `(vterm-color-white ((t (:foreground "#eeeeec"))))
 `(vterm-color-yellow ((t (:foreground "#c4a000"))))
 `(woman-bold ((t (:foreground "#1d77ff"))))
 `(woman-italic ((t (:foreground "#9f6fff"))))

 )

(provide-theme 'ots-light)
(provide 'ots-theme-light)
;;; ots-theme-light.el ends here
