#!/bin/sh

# Open files in existing Emacs window or open a new one.
# Usage: emacs [OPTION...] [FILE...]

. $HOME/.profile
export GDK_SCALE=emacs
export GTK_THEME=Adwaita:dark
export LC_ALL=C.UTF-8

# Remove stale server if Emacs crashed.
[ -z "$(ps ux | grep "/usr/bin/emac[s]")" ] && rm -rfv /tmp/emacs1000/

if [ -e /tmp/emacs1000/server ]; then
    # Open files given as arguments in already running server.
    /usr/bin/emacsclient.emacs -n "$@"
else
    # Start a new emacs, open files given as arguments and start the server.
    /usr/bin/emacs -g 90x35 --eval "(server-mode 1)" "$@" &
fi
