#!/bin/sh

# Open files in existing Emacs window or open a new one.
# Usage: emacs [OPTION...] [FILE...]

. $HOME/.profile
export LC_ALL=C.UTF-8
export RUNNING_EMACS=1
if [ -f $HOME/.emacs.d/theme-dark ]; then
    export GTK_THEME=Adwaita:dark
    sed -i 's/emacs-light/emacs-dark/' \
           ~/.config/gtk-3.0/gtk.css
else # theme-light
    sed -i 's/emacs-dark/emacs-light/' \
           ~/.config/gtk-3.0/gtk.css
fi

if [ -z "$(ps ux | grep "/usr/bin/emac[s]")" ]; then
    # Remove stale server if Emacs crashed.
    rm -rfv /run/user/1000/emacs
fi

if [ -e /run/user/1000/emacs/server ]; then
    # Open files given as arguments in already running server.
    if [ $# -gt 0 ]; then emacsclient.emacs -n "$@"; fi
else
    # Start a new Emacs, open files given as arguments and start the server.
    /usr/bin/emacs -g 90x35 --font "$(emacs-font)" --eval "(server-mode 1)" "$@" &
fi
